name: Manual Dependabot

on:
  workflow_dispatch:

jobs:
  manage_dependabot_prs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Close Dependabot PRs
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const prs = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open'
          });

          for (const pr of prs.data) {
            if (pr.user.login === 'dependabot[bot]') {
              // Close the PR
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                state: 'closed'
              });
            }
          }

    - name: Trigger Dependabot by modifying a file
      run: |
        echo "Dependabot trigger at $(date)" > .dependabot/trigger
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .dependabot/trigger
        git commit -m "Trigger Dependabot"
        git push
